install.packages("tidyverse", dependencies = TRUE)
install.packages("rmarkdown", dependencies = TRUE)
install.packages("IRkernel", dependencies = TRUE)
install.packages("skimr", dependencies = TRUE)
install.packages("deSolve", dependencies = TRUE)
install.packages("Rtsne", dependencies = TRUE)
install.packages("matlab")
install.packages("GGally")
install.packages("gridExtra")
install.packages("ppclust")
install.packages("mclust")
install.packages("rdist")
install.packages("kernlab")
install.packages("plotly")
install.packages("glmnet")
install.packages("broom")
install.packages("ggrepel")
install.packages("palmerpenguins")
install.packages("caret")
install.packages("gbm")
install.packages("httr")
install.packages("jsonlite")
install.packages("tokenizers")
install.packages("stringr")
install.packages("R6")
install.packages("digest")
install.packages("viridis")
IRkernel::installspec(user = FALSE)

system("wget https://github.com/quarto-dev/quarto-cli/releases/download/v2.12.0/quarto-2.12.0-linux-amd64.deb")
system("sudo dpkg -i quarto-2.12.0-linux-amd64.deb")
